### PR TITLE
Add preference-v14 APIs

### PR DESCRIPTION
**Pull request by Mygod**
This creates a lot of duplicate code. Maybe we should just get rid of preference-v7 APIs since we are targeting minimum API 14.

### CODE REVIEW

**Comment by Gericop** [comment]
This is not going to happen because the v14 one is based on framework classes (e.g. `android.app.Fragment`) instead of support ones (e.g. `android.support.v4.app.Fragment`) and they are not interchangable. This is also why the devs at Google didn't get rid of the v7 lib.

**Comment by Gericop** [comment]
Adding the v14 elements is a possibility though. I'll need to check some things regarding it before including those.

**Comment by Mygod** [comment]
I think it's okay to use `android.app.Fragment` for most cases. You just need to reimplement some workaround for the new APIs, for example what I did for `AlertDialog.Builder.setOnDismissListener`.

**Comment by Gericop** [comment]
I use the support fragments in my projects, even though the min SDK is usually 16 and up, simply because I don't have to care about API level differences and already using a lot of support things, so they just work together nice and easy. Thus, getting rid of v7 is a definite no-no, adding v14 is a maybe, but it's more of a "should it be in a new project or this one?" question.

**Comment by Mygod** [comment]
Well that makes sense. Look at my latest commit and you'll realize it's not quite possible to do it in two libraries with current infrastructure (`registerPreferenceFragment`).

**Comment by Mygod** [comment]
For `registerPreferenceFragment`, I suggest letting user call `registerPreferenceFragment` for proguarding.

**Comment by Gericop** [comment]
I think this will be postponed a bit since I'm not sure this approach is the best due to the mixing of the different versions of preferences.

**Comment by Mygod** [comment]
Actually is there an advantage to prefer native fragments to support lib ones now that the min API is 14?

**Comment by Gericop** [comment]
What do you mean?

**Comment by Mygod** [comment]
Oh I mean is there a reason to use native fragments instead of the ones in the support library? It seems that the only reason is that it would (possibly) make the binary smaller.

**Comment by Gericop** [comment]
You mean the native preference fragments? Or fragments in general? I guess if you don't want to include the support library because you target API 21+ and use the native material stuff, then you don't use the support fragments. IMO it's just easier to use the support ones because I don't have to care about the different API levels.

**Comment by Mygod** [comment]
I don't think there's anything material design for Fragment in support library though, is it?

**Comment by Gericop** [comment]
The `AppCompat` theming itself provides material design.

**Comment by Mygod** [comment]
I think the theming also applies to native Fragments though.

**Comment by Gericop** [comment]
Yes it does, but you need the AppCompat for that or the material is not used on pre-lollipop devices.

**Comment by DreaminginCodeZH** [comment]
I think Google will continue using support Fragments and this has been the case for years since they stopped updating ViewPager v14 etc for native Fragment. Support Fragment also provides access to new API even after v14 (e.g. permission callback, transition, isStateSaved), so in the next upcoming years I think it will still be what most developers should be using.

**Comment by Gericop** [comment]
It seems like this pull request can be closed as Android P will [deprecate native fragments](https://github.com/android/android-ktx/pull/161#issuecomment-363270555).

**Comment by Gericop** [comment]
Closing this pull request because the native [`Fragment`](https://developer.android.com/reference/android/app/Fragment) class was deprecated in API level P.

**Pull request closed without merging**
