### PR TITLE
Update ColorPicker version

### PR DESCRIPTION
**Pull request by tcqq**
Fix ColorPicker bug.

### CODE REVIEW

**Comment by Gericop** [comment]
This has been added already but it's only available on the develop branch.

**Comment by TCQQ** [comment]
ColorPicker new version is 1.0.3, but In “com.takisoft.fix:preference-v7-extras:27.0.2.0” the “fix:colorpicker” version is 1.0.2

**Comment by Gericop** [comment]
Like I said, it's only available on the develop branch. It hasn't been released yet.

**Comment by TCQQ** [comment]
Yes, update it ok?

**Comment by Gericop** [comment]
Has been updated separately in **v27.1.0.0**

**Pull request closed without merging**
