### PR TITLE
Fix scrollbars

### PR DESCRIPTION
**Pull request by Mygod**
This solution is based on NeoSpb's (see #12). Yet simpler and more flexible I think.

I haven't thoroughly tested this but it should work and you should get the idea. :smile:

### CODE REVIEW

**Comment by Gericop** [comment]
I finally had some time to review the things. As I see, you still don't need to use reflections nor custom classes. Calling `getListView().scrollBy(0, 0)` in `onResume()` does the same thing. Quoting from the description of [`awakenScrollBars()`](http://developer.android.com/reference/android/view/View.html#awakenScrollBars%28%29):
> This method is automatically invoked by scrollBy(int, int) and scrollTo(int, int).

**Comment by Mygod** [comment]
You're right! I've updated it now.

**Comment by Gericop** [comment]
I wish we could just enable vertical scrollbars from code instead of using custom styles for that. I was trying to debug the process of initializing scrollbars in a `View` because calling certain methods seems to do the same thing as declaring `scrollbars="vertical"` in the layout (*or in the styles in our case*), but no luck so far...

**Comment by Mygod** [comment]
If I remember correctly, it's easier to disable scrollbars than enable them in code because of a bug.

**Comment by Mygod** [comment]
http://gph.is/2csjxsu

**Comment by Gericop** [comment]
Is this really needed? Even the settings in Android has no scrollbars (at least on my HTC).

**Comment by Mygod** [comment]
@Gericop There is one on my Lineage OS 14.1.

**Comment by Gericop** [comment]
Checked this, the Java modification is not needed anymore, the scrollbars automatically show up and fade away with the XML only. If I can create a solution such that the scrollbars can be turned on / off with a single XML attribute, I'll add it to the styles.

**Comment by Mygod** [comment]
I don't think it hurts to have a scrollbar.

**Comment by FranckRJ** [comment]
I would like to have a scrollbar too, Settings on Android 8.0 (Nexus 5X) has a scrollbar.

**Comment by Gericop** [comment]
Scrollbars enabled in v**27.0.0.0**

**Pull request closed without merging**
