### PR TITLE
Refactor to AndroidX

### LINKED ISSUE #146: Upgrade to support library v28.0.0-alpha1

### PR DESCRIPTION
**Pull request by Mygod**
Fix #146. TODO:

* [x] Rename to `com.takisoft.preferencex`;
* [x] BUG: Scrollbars in SeekbarPreference?

Continuing discussion in #171, I think it's best to [rename this repo with redirection](https://blog.github.com/2013-05-16-repository-redirects-are-here/) and keep the old code in another branch. Also I'd like to change version scheme if you don't mind (see https://github.com/Gericop/Android-Support-Preference-V7-Fix/commit/2549217012264c3a3f8554633dde24f3c103a12b).

### CODE REVIEW

**Comment by Mygod** [comment]
@Gericop Ready to merge.

**Comment by Mygod** [comment]
@Gericop Ready to merge.

**Comment by Gericop** [comment]
Going to test it thoroughly and hopefully release it tomorrow to bintray.

**Comment by Mygod** [comment]
Any updates?

**Comment by Gericop** [comment]
Working on it right now but my Android Studio is being an idiot. First it launched the app which crashed due to "missing MyApplication" class (wtf? it's there...) and now it just wouldn't recognize the project as an Android one anymore...

**Comment by Gericop** [comment]
At least the bintray repo is set up at https://bintray.com/takisoft/android.

**Comment by Mygod** [comment]
Awesome! You should try clean project + invalidate cache and restart. 🤣

**Comment by Gericop** [comment]
I found one error so far: the `applicationId` was set to `com.takisoft.preferencefix` in the gradle file instead of `com.takisoft.preferencex.demo`. Changing it and cleaning the project helped 😅

**Comment by Gericop** [comment]
Well, on API 15 and 17 (so probably below API 21) the `SeekBarPreference` has bad padding.

API 15 | API 17
--- | ---
screenshot_1531483967 | screenshot_1531483976

**Comment by Mygod** [comment]
Hmm yeah I didn't test API <19. 😅

**Comment by Gericop** [comment]
Well, found the other "easter egg":

This is how the `SeekBar` is aligned with the title:

```xml
android:paddingStart="@dimen/preference_seekbar_padding_start"
android:paddingEnd="@dimen/preference_seekbar_padding_end"
```
which just doesn't work, the paddings in the emulator are symmetrical instead of being 0dp on the left and 22dp on the right. How to fix it? Add the `paddingLeft` and `paddingRight` attributes too:

```xml
android:paddingStart="@dimen/preference_seekbar_padding_start"
android:paddingLeft="@dimen/preference_seekbar_padding_start"
android:paddingEnd="@dimen/preference_seekbar_padding_end"
android:paddingRight="@dimen/preference_seekbar_padding_end"
```
Now the `SeekBar` is aligned with the text above it. And where's the fun, you might ask. Well:
> Redundant attribute paddingLeft; already defining paddingStart with targetSdkVersion 28.
> Redundant attribute paddingRight; already defining paddingEnd with targetSdkVersion 28.

_I mean, c'mon Google, get your shit together..._

**Comment by Gericop** [comment]
Reported it: https://issuetracker.google.com/issues/111405638

**Comment by Gericop** [comment]
Also, committed a patch to the AOSP to fix this in AndroidX:
https://android-review.googlesource.com/c/platform/frameworks/support/+/717258

**Comment by Mygod** [comment]
Huh nice. I'm guessing that not even Google cares about Android 4.x any more.

BTW how do you contribute to AOSP?

**Comment by Gericop** [comment]
Yeah, I get that Android 4.x is pretty old but if they officially support it by setting the minSdk to 14 then they should test everything at least once...

Check out the [Submitting Pathes](https://source.android.com/setup/contribute/submit-patches) guide for details about how to contribute to AOSP.

**Comment by Mygod** [comment]
Thanks! Seems pretty complicated...

> Redundant attribute paddingLeft; already defining paddingStart with targetSdkVersion 28.
> Redundant attribute paddingRight; already defining paddingEnd with targetSdkVersion 28.

I think that's just a warning. You can suppress it using `tools:ignore="RtlHardcoded"`. Is there anything else that's holding this release back? I just tested it on API 19 and it seems to work fine.

**Comment by Mygod** [comment]
Looks good! I'm already starting to use it in my own project. Kudos to you!

**Comment by Gericop** [comment]
Meanwhile it became available on jcenter, so you don't need to specify the repo URL separately.

**Comment by Gericop** [comment]
@Mygod Funny thing is, I reported the [issue](https://issuetracker.google.com/issues/111405638) about the `SeekBarPreference`'s bad paddings, the assigned guy asks for a sample project, but I just cannot reproduce it on API 17 in a new project. Tried to strip the sample project in this lib so that it would look like the one in the new project and it reproduces the issue... WTF? 😅 I just don't understand...

**Comment by Gericop** [comment]
Oh wow. So found the single attribute that decides whether it produces the error or not: `android:supportsRtl` in the manifest. If it's set to `true`, the paddings are good on API 17 (API 15 still looks bad) but if it's `false` (defaults to that), the `paddingStart` and `paddingEnd` attributes are not interpreted on pre-Lollipop devices.

**Comment by Gericop** [comment]
No need in my opinion as the lib contains the fixed layout files, and as soon as the patch gets reviewed and merged (and released ofc), I'll remove them.

**Comment by Mygod** [comment]
Sounds good.

**Comment by feelfreelinux** [comment]
@Gericop @Mygod Hi, thanks a lot for this lib, helped me a lot in my projects. However, after updating to androidx, all of my settings fragment got additional margin from the left (As seen in this screenshot: https://user-images.githubusercontent.com/5181621/42691091-fdd97c6c-86a6-11e8-891f-a2460035e182.png) 
Is there any way to disable it? Tried to @null icon / etc but it didn't work.

**Comment by Gericop** [comment]
That's because the new design reserves the icon space automatically so if you set an icon on one or more preferences, it wouldn't look awkward. That being said, you can turn it off by setting the `app:iconSpaceReserved` to `false` on every preference in the XML.

**Comment by feelfreelinux** [comment]
@Gericop Thanks, will test it out. The next thing i noticed, is that onSharedPreferenceChanged is not getting called at all. Its inflated by replacing FrameLayout with fragment from parent activity.

**Comment by feelfreelinux** [comment]
Btw, #132 still occures in alpha01

**Comment by Gericop** [comment]
@feelfreelinux What do you mean `onSharedPreferenceChanged` is not getting called? It works in the sample app.

**Comment by feelfreelinux** [comment]
@Gericop Oh, my fault. During AndroidX refactor, I accidentally removed `onResume` override where I was setting `onSharedPreferenceChanged`. Thanks a lot.

**Comment by Gericop** [comment]
It seems like the icon (and the space for it) is handled differently in the category layout than in a preference, and thus it does not work. I'll file a bug with Google and provide a bug fix in this lib until it gets resolved officially.

**Comment by Gericop** [comment]
@adrcotfas @feelfreelinux Reopened the #132 issue. Also, published v**1.0.0-alpha2** that contains the bug fix for this problem.

**Pull request merged**
