### PR TITLE
Update library for 28.0.0-alpha3

### PR DESCRIPTION
**Pull request by Mygod**
P.S. It seems like most (if not all) code in this library isn't about FIX anymore.

### CODE REVIEW

**Comment by Gericop** [comment]
This lib still fixes some issues, e.g. the preference category color not being set to the accent color on pre-lollipop devices.

**Comment by Mygod** [comment]
I just noted that a few days back Google released androidx 1.0.0-beta01 without updating the old library to 28.0.0-beta01. I think it's time to upgrade in which case we can delete whatever we want.

**Comment by Gericop** [comment]
The androidx version will reside in a new repo with new artifact names so that's a different story. The 28.0.0 version will be the last stable version of the support lib so this artifact of the lib (28.0.0.x) will live till that.

**Comment by Mygod** [comment]
@Gericop I don't see any progress on that. Have you started working on the new repo? I can start porting code now. What do you think of `com.takisoft.preferencex`?

**Comment by Gericop** [comment]
I haven't started working on it yet, only created the repo (lol). That name sounds good to me. I can add you as a collaborator to the repo so you can push the code there if you want.

**Comment by Mygod** [comment]
Okay. Closing this for now.

**Pull request closed without merging**
