### PR TITLE
Add SimpleMenuPreference by @RikkaW

### PR DESCRIPTION
**Pull request by Mygod**
Refactor @RikkaW's SimpleMenuPreference into Android-Support-Preference-V7-Fix. I'm not sure if @RikkaW is okay with this.

~Changes other than renaming things to make it work: SimpleMenuPreference.java:49 hardcoded popupStyle. May need changing later.~ Fixed.

Source: https://github.com/RikkaW/MaterialPreference/tree/3cd912395deddc666619da76425895d84577db25/preference-simplemenu

Only tested on Android API level 27.

### CODE REVIEW

**Comment by Gericop** [comment]
Copying it over should be okay since it's under Apache v2 license. I'll test it on older APIs and see about the popupStyle though.

**Comment by Mygod** [comment]
Is it gonna take another nine months to get merged? 😢

**Comment by Gericop** [comment]
Not really, I've just had some work to do.

**Comment by Mygod** [comment]
Tested on Android 4.4. Should be good enough to merge.

**Comment by Gericop** [comment]
Does it _have_ to fall back to `ListPreference` on pre-Lollipop? Haven't had time to test it yet. Which part requires API 21+?

**Comment by Mygod** [comment]
You mean you want it to fallback to `DropDownPreference` instead? That should be doable as well.

**Comment by Gericop** [comment]
No, I meant why can't pre-Lollipop display it just like an API 21+ device? With the simple menu style and whatnot. Is there a particular call / view / style that requires API 21+?

**Comment by Mygod** [comment]
Okay I did a quick test. It turns out that it's missing elevation and enter animation. Everything else works fine on Android 4.4.

**Comment by Mygod** [comment]
Great. Only 8.25 months to go. 😃

**Comment by Gericop** [comment]
Testing now

**Comment by Gericop** [comment]
Merged. It will be released in v**27.0.1.1**.

**Pull request merged**
