### PR TITLE
Remove obsolete resources

### PR DESCRIPTION
**Pull request by Mygod**
A lot of fixes in this library is irrelevant now and can be removed.

### CODE REVIEW

**Comment by Gericop** [comment]
The `preference_dialog_edittext.xml` layout file should not be removed since it is used by `EditTextPreferenceDialogFragmentCompat` for the dialog. The material style sets the preference's layout but not the dialog's.

**Comment by Mygod** [comment]
I don't think it's used anywhere. Let me double check in a moment.

**Comment by Gericop** [comment]
```
PreferenceThemeOverlay.v14.Material
- editTextPreferenceStyle
  - Preference.DialogPreference.EditTextPreference.Material
    - Preference.DialogPreference.EditTextPreference
      - android:dialogLayout -> @layout/preference_dialog_edittext
```

**Comment by Mygod** [comment]
Oh I see. You're overwriting the old layout file.

**Comment by Mygod** [comment]
Fixed. Please review again.

**Pull request merged**
